title: Brian Pinto
logo: /assets/images/self.png
description: As a data scientist, I utilize data to generate insights that help businesses strategize optimally. My educational background in mathematics and philosophy, along with my varied work history, has propelled me to develop skills in analyzing data and generating intelligible reports. 
#show_downloads: true
theme: jekyll-theme-minimal
